name: project
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  string_validator: ^0.3.0
  cupertino_icons: ^1.0.2
  phosphor_flutter: ^1.4.0
  table_calendar: ^3.0.7
  intl: ^0.17.0
  firebase_core: ^2.1.0
  firebase_auth: ^4.0.2
  google_sign_in: ^5.4.2
  flutter_login_facebook: ^1.6.2
  cloud_firestore: ^4.0.3
  flutter_riverpod: ^2.1.1
  uuid: ^3.0.4
  firebase_storage: ^11.0.6
  path: ^1.8.0
  image_picker: ^0.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Light.ttf
          weight: 300
        - asset: assets/fonts/Comfortaa-Regular.ttf
        - asset: assets/fonts/Comfortaa-Medium.ttf
          weight: 500
        - asset: assets/fonts/Comfortaa-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700
